### PR TITLE
Only support ruby 2.2+ and bump major version

### PR DESCRIPTION
**Pull request by claytron**
While 2.1 is still in security maintenance, it will be fully EOL before
too long. Might as well stop testing against it now.

This also adds Ruby 2.4 to the travis config.

Rubocop fixes:

- Adds space after encoding line to appease the `Style/EmptyLineAfterMagicComment` cop (added in `0.48`)
- Explicitly disable `Style/NumericLiterals`, the exclude was not working.

### CODE REVIEW

**Comment by jakeonrails** [comment]
Hi @claytron thank you for contributing. Tests are legitimately failing on this branch, I think because now a newline is getting added after the `#encoding` line in the generated `db/schema.rb`. Can you update the spec to include this extra newline inside the `reference_db_schema` method? That should make Travis happy.

Also, feel free to add your username/link to github/twitter/etc in the Contributors section of the README.

Once we get Travis passing I'm a 👍  on getting this merged, and I'll cut a new version and push to Rubygems.

**Comment by jakeonrails** [comment]
....aaaand I just realized what you were trying to say in #18 . Yes please merge the other changes into this branch as well, that will make it easier to get it all working together. I'm on board for all your recommendations!

Again, thank you very much! :)

**Comment by claytron** [comment]
Pulled that other branch in here and added myself to the README. All green now!

**Comment by jakeonrails** [comment]
Awesome, thanks for your work, @claytron. I've pushed version 3.0.0.

**Pull request merged**
