### PR TITLE
Moving db.rake so gem can be more explicit about loading its own file

### PR DESCRIPTION
**Pull request by TCampaigne**
Ran into a very strange issue that this gem's rake task additions simply weren't running. Tracked down the issue to the project also having a `db.rake` file.

Making the gem more explicit about the rake task path being its own means there shouldn't be any such naming collisions (Similar to how rspec loads its rake tasks https://github.com/rspec/rspec-rails/blob/c1de0e2ced37f1a005fd16948a770661d34264e6/lib/rspec-rails.rb#L19).

### CODE REVIEW

**Comment by masterful** [comment]
We'll actually need to update the `../../../` relative path inside `db.rake` as well - or else rubocop will complain about not being able to find its configuration file.

**Comment by jakeonrails** [comment]
@TCampaigne are you able to make the change suggested by @masterful? I can merge your branch and then make the change separately but it'd be cleaner to have that second commit in the same branch/PR. Also, thank you for your contribution! I've been using this gem in my own projects for the last year, but it's awesome to know that others are getting something out of it too!

**Comment by TCampaigne** [comment]
@masterful Good call! Branch has been updated.

**Comment by TCampaigne** [comment]
@jakeonrails Yeah, schema's have been a huge pain point of mine for a while. We've been using this gem in one project for a little while now, but this issue came up when I tried applying it to another one. Happy to be able to contribute back!

**Comment by jakeonrails** [comment]
Cool, I tested it and it works as promised. Getting this merged now, and I will soon cut a new release. I'll let you know when it's live so you can update your Gemfiles.

**Comment by jakeonrails** [comment]
@TCampaigne 1.0.2 is now available! Thanks a bunch!

https://rubygems.org/gems/fix-db-schema-conflicts/versions/1.0.2

**Pull request merged**
