### PR TITLE
Remove alias_method_chain in favor of Module#prepend

### LINKED ISSUE #9: Deprecation warnings in Rails 5
In Rails 5, `alias_method_chain` has been deprecated. It's being used in `lib/fix_db_schema_conflicts/schema_dumper.rb`:

```ruby
def extensions_with_sorting(*args)
  with_sorting do
    extensions_without_sorting(*args)
  end
end
alias_method_chain :extensions, :sorting

def table_with_sorting(*args)
  with_sorting do
    table_without_sorting(*args)
  end
end
alias_method_chain :table, :sorting
```

### PR DESCRIPTION
**Pull request by jensljungblad**
Fixes #9

### CODE REVIEW

**Comment by jakeonrails** [comment]
Looks good. Specs are passing for most Rubies. I'll play with it in person and see if I can get it passing locally on 2.2. I keep having trouble getting bundler to play well on Travis for some reason. It'll work on one version of Ruby and break on another.

Great job, and thank you for your work!

**Comment by jakeonrails** [comment]
Just merged, will be bumping the version soon.

**Comment by jensljungblad** [comment]
Thanks!

**Comment by jakeonrails** [comment]
We are now at 2.0.0. Thanks for your help, I've added you to the contributor list.

**Pull request merged**
