### PR TITLE
renamed 'Layout/AlignHash' to 'Layout/HashAlignment'

### PR DESCRIPTION
**Pull request by asalgan**

### CODE REVIEW

**Comment by delucas** [comment]
@jakeonrails please merge this :pray: 
Thanks!!

**Comment by tunacasserole** [comment]
I need this change as well.  I'm on Rubocop 0.82.

**Comment by OttilieWilliams** [comment]
Hi @jakeonrails, would also be very grateful if you could merge this :) 

It keeps coming up as an error every time we use it!

```
Dumping database schema with fix-db-schema-conflicts gem
Error: The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
```

**Comment by cprodhomme** [comment]
any news ? cc @jakeonrails

**Comment by luizkowalski** [comment]
I would need this. @jakeonrails is there anything we could do to help you get this merged?

**Comment by LE-HU** [comment]
bump

**Comment by MarcoMatarazzo** [comment]
@jakeonrails you there? :-)

**Comment by jemminger** [comment]
@jakeonrails has had zero activity for all of 2020.  It might be time to fork this

**Comment by jakeonrails** [comment]
I have offered for some people who've reached out directly to allow  others to maintain this repo/gem as I do not have time anymore. @jemminger would you be interested?

**Comment by cmoylan** [comment]
@jakeonrails I'll maintain it.

**Comment by rizalmuthi-ap** [comment]
any update on this @cmoylan 
Thanks 🙇

**Comment by cmoylan** [comment]
> any update on this @cmoylan
> Thanks 🙇

I haven't been granted write access to the repository yet. Can't merge this PR.

**Comment by rizalmuthi-ap** [comment]
Ping @jakeonrails

**Comment by raviiitb** [comment]
Ping @jakeonrails. You can grant access to @cmoylan

**Comment by bak1an** [comment]
Should be fixed now with #41

**Pull request closed without merging**
